services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: hrconnect
      POSTGRES_PASSWORD: hrbackenddb
      POSTGRES_DB: hr
    ports:
      - "9002:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - hrbackend

networks:
  hrbackend:
