services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - hrbackend

  redis:
    image: redis:8.6-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./users.acl:/usr/local/etc/redis/users.acl
      - ./data/redis:/data
    networks:
      - hrbackend

  s3:
    image: dxflrs/garage:v2.3.0
    command: /garage server --single-node --default-bucket
    environment:
      GARAGE_DEFAULT_SECRET_KEY: ${GARAGE_S3_SECRET}
      GARAGE_DEFAULT_ACCESS_KEY: ${GARAGE_S3_ACCESS}
      GARAGE_DEFAULT_BUCKET: ${GARAGE_S3_BUCKET}
      GARAGE_RPC_SECRET: ${GARAGE_RPC_SECRET}
    ports:
      - "${GARAGE_S3_PORT}:3900"
    volumes:
      - ./garage.toml:/etc/garage.toml
      - ./data/garage:/var/lib/garage
    networks:
      - hrbackend

networks:
  hrbackend:
